export const items = [
  {
    id: 1,
    title: "Samsung Galaxy S21",
    category: "Electronics",
    price: 799,
    description:
      "Latest smartphone from Samsung with stunning display and camera.",
  },
  {
    id: 2,
    title: "Nike Running Shoes",
    category: "Clothing",
    price: 120,
    description: "Comfortable and stylish running shoes for all terrains.",
  },
  {
    id: 3,
    title: "The Catcher in the Rye",
    category: "Books",
    price: 15,
    description: "A classic novel written by J.D. Salinger.",
  },
  {
    id: 4,
    title: "Sony 4K Ultra HD TV",
    category: "Electronics",
    price: 999,
    description: "Experience cinematic viewing with stunning 4K clarity.",
  },
  {
    id: 5,
    title: "Adidas Sports Jacket",
    category: "Clothing",
    price: 60,
    description: "Lightweight and water-resistant sports jacket.",
  },
  {
    id: 6,
    title: 'MacBook Pro 16"',
    category: "Electronics",
    price: 2399,
    description: "Apple’s powerful laptop for professionals with M1 chip.",
  },
  {
    id: 7,
    title: "Harry Potter and the Philosopher's Stone",
    category: "Books",
    price: 20,
    description: "The first book in the beloved Harry Potter series.",
  },
  {
    id: 8,
    title: "Dell XPS 13 Laptop",
    category: "Electronics",
    price: 999,
    description: "Lightweight and powerful laptop with a stunning display.",
  },
  {
    id: 9,
    title: "Levi’s Denim Jacket",
    category: "Clothing",
    price: 90,
    description: "Classic denim jacket that never goes out of style.",
  },
  {
    id: 10,
    title: "Atomic Habits",
    category: "Books",
    price: 25,
    description:
      "A bestselling book on building good habits and breaking bad ones.",
  },
  {
    id: 11,
    title: "Beats Studio3 Wireless Headphones",
    category: "Electronics",
    price: 349,
    description: "High-performance wireless noise-canceling headphones.",
  },
  {
    id: 12,
    title: "Fitbit Charge 4",
    category: "Electronics",
    price: 129,
    description: "Advanced fitness tracker with heart rate monitoring and GPS.",
  },
  {
    id: 13,
    title: "Puma Workout Pants",
    category: "Clothing",
    price: 45,
    description: "Comfortable workout pants for training and gym sessions.",
  },
  {
    id: 14,
    title: "To Kill a Mockingbird",
    category: "Books",
    price: 18,
    description: "A Pulitzer Prize-winning novel by Harper Lee.",
  },
  {
    id: 15,
    title: "Apple iPad Pro",
    category: "Electronics",
    price: 1099,
    description:
      "Apple’s powerful tablet with a stunning display and versatile usage.",
  },
];
